version: '2'
services:
  redis:
    image: redis:3.2-alpine
    command: ["redis-server"]
    hostname: redis
    ports:
          - 6379:6379

  postgres:
      image: postgres:10.4
      ports:
          - 5432:5432
      environment:
        POSTGRES_DB: trainmapper